### PR TITLE
move build metadata into pyproject.toml

### PR DESCRIPTION
**Pull request by zacharyburnett**
align with PEP621 metadata standards and `setuptools>=61.2` build with PEP517

### CODE REVIEW

**Comment by zacharyburnett** [comment]
failing tests seem to be the same as on the main branch: https://github.com/spacetelescope/ullyses/actions/runs/4359794031/jobs/7621979281#step:5:1089
```
def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by tapastro** [comment]
Outdated PR, work done in #78.

**Comment by tapastro** [comment]
Actually, there were some updates here to the testing workflow that may be useful? I may have been hasty in closing this.

**Comment by zacharyburnett** [comment]
> Outdated PR, work done in #78.

Great! I did notice however that the main dependencies require `setuptools`:
https://github.com/spacetelescope/ullyses/blob/6f5d101b046802b9961f80a2d748327cebdf0d2d/pyproject.toml#L25
but I can't find any usages of `setuptools` in the code itself; is that included by error?

**Comment by tapastro** [comment]
Very much likely - I guess the build-requires section gets setuptools for pyproject installs, but it isn't required to be listed in the dependency list, as the package itself doesn't need it?

**Pull request closed without merging**
