### PR TITLE
DR7 release restructure

### PR DESCRIPTION
**Pull request by tapastro**
This moves the code to a src directory, builds using a pyproject.toml file, adds custom metadata in the release version to ullyses.__release__ and will have an entry point soon.

### CODE REVIEW

**Comment by tapastro** [comment]
This will fail testing until the ullyses-utils 3.0.0 is released, as it is set as a lower pin on the dependency.

**Comment by tapastro** [comment]
Had to remove the attempt to store the release metadata in a pyproject tool table, as the pyproject.toml file is not installed from a wheel, meaning the metadata is lost if not given explicitly in the package src/ directory. So now it's done via a clunky release.py file. ☹️

**Review by jotaylor — APPROVED** [review]
Using the DR7 release version of ullyses_utils, this install works as expected, the entrypoint (and coadd) works, and importing the release version is successful.

**Comment by tapastro** [comment]
Closed in favor of #78

**Pull request closed without merging**
